### ISSUE TITLE
If capture doesn't open, error message is not helpful.

### ISSUE THREAD

**Issue by LenOttSocketMobile** [SocketMobile/singleentry-js#2]
So in Brave, there is some permissions error and the error message is:
`Status: opening Capture error: [object Object]`

**Comment by mcsocket** [comment]
Confirming app errors showing up more clearly.

![Screenshot 2023-06-05 at 10 24 01 AM](https://github.com/SocketMobile/singleentry-js/assets/88163125/054bef9a-9613-4196-a806-928d8874d626)
